config/routes.rb
Rails.application.routes.draw do
  get 'user_reports/new'
  get 'user_reports/create'
  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth' }
  root "posts#index"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index, :new, :edit, :update, :destroy] do
    collection do
      post :index, :feed, :maps
    end
    resources :comments, only: [:create, :update, :destroy]
  end
  post '/posts/create', to: 'posts#create'
  resources :user_reports, only: [:new, :create]
  post '/posts/:id/like' => 'posts#like', as: :like_post
  post '/posts/:id/dislike' => 'posts#dislike', as: :dislike_post
  post '/posts/:id/favorite' => 'posts#favorite', as: :favorite_post
  resources :relationships,       only: [:create, :destroy]
  get '/users/:id/show_favorite', to: 'posts#show_favorite', as: :favorite_show
  get '/feed', to: 'posts#feed'
  get '/maps', to: 'posts#maps'
  get '/maps/:title', to: 'posts#maps'
  get '/info', to: 'posts#info'
  post '/users/:id/verified' => 'users#verified', as: :verified_user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed, dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower, dependent:   :destroy
  has_one_attached :avatar, dependent:   :destroy
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  
  def set_default_role
    self.role ||= :user
  end
  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  def self.create_from_provider_data(provider_data)
      where(provider: provider_data.provider, uid:provider_data.uid).first_or_create do |user|
        user.email = provider_data.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = provider_data.info.name
      end
  end

  def self.from_omniauth(auth)
    name_split = auth.info.name.split(" ")
    user = User.where(email: auth.info.email).first
    user ||= User.create!(provider: auth.provider, uid: auth.uid, last_name: name_split[0], first_name: name_split[1], email: auth.info.email, password: Devise.friendly_token[0, 20])
      user
  end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, :except => [:show]
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy,:following, :followers]
    def index
      @current_view = 'users/index'
      @users = User.all
      if params[:user_name].present?
        @users = User.where("name LIKE ? OR username LIKE ?", "%#{params[:user_name]}%", "%#{params[:user_name]}%")
      else 
        @users = User.all
      end
    end
    
    def edit
      @user = User.find(params[:id])
    end
    
    def show
      @current_view = 'users/show'
      @user = User.find(params[:id])
      @id= User.find(params[:id]).id
      @posts= Post.where(user_id: params[:id])
      @pagy, @posts = pagy_countless(Post.where(user_id: params[:id]), items: 5)
      @comment = Comment.new
    end
  
    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to  user_path(current_user.id), :notice => "User updated."
      else
        redirect_to user_path(current_user.id), :alert => "Unable to update user."
      end
    end
    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to posts_url, :notice => "User deleted."
    end
    def verified
      @user = User.find(params[:id])
      if @user.verified == 1
        @user.update_attribute(:verified, 0)
      else
        @user.update_attribute(:verified, 1)
      end
    end
    private
    
    def admin_only
      unless current_user.admin?
          redirect_to posts_url, :alert => "Access denied."
      end
  end
    
    def user_params
        params.require(:user).permit(:avatar, :name, :surname, :username, :phone, :email)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.
                          build(followed_id: @user.id),
                          remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <a class="btn feed-link"><%= f.submit "SEGUI", class: "btn feed-link", style: "width:100%; color: #1169B2" %></a>
<% end %>

app/views/users/_follow_form.html.erb
<div class="container" style="width: 60%;">
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col-10">
      <% unless current_user==(@user) %>
        <div id="follow_form"  style="width: 200px; padding-left: 45px">
        <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
        <% else %>
          <%= render 'follow' %>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div>
    <% if user.avatar.attached? %>
      <%= image_tag(user.avatar, style:"width: 100px") %>
    <% else %>
      <%= image_tag("default_avatar.jpg", style:"width: 100px") %>
    <% end %>
    <%= form.file_field :avatar %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :surname, style: "display: block" %>
    <%= form.text_field :surname %>
  </div>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <a class="btn delete-link"><%= f.submit "UNFOLLOW", class: "btn delete-link", style: "width:100%; color: #c02635" %></a>
<% end %>

app/views/users/_user.html.erb
<div  id="<%= dom_id user %>"  style="background-color: white;">
  <div class="row" style="margin-top: 80px;">
    <div class="row" style="margin-top: 40px; text-align: left; display: flex; align-items: center;">
      <div class="col-3"></div>
      <div class="col-3">
        <% if user.avatar.attached? %>
          <%= image_tag(user.avatar, style:"width: 70%") %>
        <% else %>
          <%= image_tag("default_avatar.jpg", style:"width: 70%") %>
        <% end %>
      </div>
      <div class="col-6">
        <div class="row">
          <div class="col-12">
          <h2 id="<%= user.id %>" class="name" style="display: inline-block;"><%= user.name %><%= user.surname %></h2>
          <% if user.verified==1 %>
            <%= image_tag("verified-icon.jpg", style:"width: 20px; display: inline-block; padding-bottom: 5px;", class:"verified-icon", id:user.id) %>
          <% end %>
          </div>
          <div class="col-12">
          <h5 id="<%= user.id %>" class="username">@<%= user.username %></h5>
          </div>      
          <div class="col-12">
          <strong id="<%= user.id %>" class="email"><%= user.email %></strong>
          </div>      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container' style="width: 60%; background-color:white; text-align:center;">
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back", @user %> 
</div>
</div>

app/views/users/index.html.erb
<p class="alert alert-danger" style="z-index: 1; margin-top: 78px; position: absolute;"><%= alert %></p>
<p class="alert alert-success" style="z-index: 1; margin-top: 78px;position: absolute;"><%= notice %></p>
<div id="users" class="container-fluid" style="padding-top: 100px; width: 60%; ">
  <% @users.each do |user| %>
    <%= render user %>
    <div class="container" style="background-color: white;">
      <div class="row" style="padding-top: 20px; height: 40px;">
        <div class="col-4"style="display: flex"></div>
        <div class="col-4" style="text-align: center;display: flex">
          <a class="btn feed-link"><%= link_to "Visualizza profilo", user, class: "btn feed-link", style: "margin-bottom: 100px;" %></a>
        </div>
        <div class="col-4"style="display: flex"></div>
      </div>
      <div class="row" style="padding-top: 20px;">
        <%if can? :all, @user%>
          <% if user.verified == 1 %>
            <div class="col-12" style="display: flex">
              <%= button_to "Elimina verificato", verified_user_path(user), class: 'btn delete-link unverified-btn', style: 'color: #c02635', id:user.id %> 
            </div>
          <% else %>
            <div class="col-12" style="display: flex">
              <%= button_to "Conferma verificato", verified_user_path(user), class: 'btn feed-link verified-btn', style: 'color: #1169B2', id:user.id %> 
            </div>
          <% end %>
        <%end%>
      </div>
    </div>
      
  <% end %>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var alerts = document.querySelectorAll(".alert");

    alerts.forEach(function(alert) {
      if (alert.innerHTML.trim() !== "") {
        alert.classList.add("show");
      }
    });
  });

</script>

app/views/users/show.html.erb
<p class="alert alert-danger" style="z-index: 1; margin-top: 78px; position: absolute;"><%= alert %></p>
<p class="alert alert-success" style="z-index: 1; margin-top: 78px;position: absolute;"><%= notice %></p>
<br>
<div style=" width: 60%; text-align: center; align-items: center; justify-content:center; margin-left: 255px; background-color: white;" class="align-items-center flex align-items-center ">
  <div style="text-align: center; justify-content:center;" class="align-items-center">
  <%= render @user %>

  <section class="stats" style="background-color: white">
    <%= render 'shared/stats' %>
  </section>
  <%= link_to image_tag("pencil.jpg", style: "width: 50px;"), new_post_path, class: "btn pencil"%>
  <%= render 'follow_form' if user_signed_in? %>
  <%if can? :all, @user or (current_user!=nil and current_user.id == @id)%>
    <br>
    <div>
      <div class="row" style="background-color: white; margin: 0;">
        <div class="col-2"></div>
        <div class="col-3" style="text-align:center;">
          <%= link_to "Modifica profilo", edit_user_path(@user), class: "btn feed-link"  %> 
        </div>
        <div class="col-1" style="text-align:center;">
          <%= link_to "Preferiti", favorite_show_path(@user), class: "btn feed-link"  %> 
        </div>
        <div class="col-2" style='text-align: center; display: contents;'>
          <%= form_tag @user, method: :delete, style:'margin-left: 80px; margin-top: -4;' do %>
            <%= button_to "Elimina profilo", @user, method: :delete, class: "btn delete-link" %>
          <% end %>
        </div>
        <div class="col-4"></div>
      </div>
    </div>  
  <%end%>
  </div>
</div>
<hr>
<div class="container" style="width: 60%;">
  <h1>Post:</h1>
  <% @posts.each do |post| %>
    <%= render post %>
  <% end %>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    var alerts = document.querySelectorAll(".alert");

    alerts.forEach(function(alert) {
      if (alert.innerHTML.trim() !== "") {
        alert.classList.add("show");
      }
    });
  });

</script>