config/routes.rb
Rails.application.routes.draw do
  get 'user_reports/new'
  get 'user_reports/create'
  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth' }
  root "posts#index"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index, :new, :edit, :update, :destroy] do
    collection do
      post :index, :feed, :maps
    end
    resources :comments, only: [:create, :update, :destroy]
  end
  post '/posts/create', to: 'posts#create'
  resources :user_reports, only: [:new, :create]
  post '/posts/:id/like' => 'posts#like', as: :like_post
  post '/posts/:id/dislike' => 'posts#dislike', as: :dislike_post
  post '/posts/:id/favorite' => 'posts#favorite', as: :favorite_post
  resources :relationships,       only: [:create, :destroy]
  get '/users/:id/show_favorite', to: 'posts#show_favorite', as: :favorite_show
  get '/feed', to: 'posts#feed'
  get '/maps', to: 'posts#maps'
  get '/maps/:title', to: 'posts#maps'
  get '/info', to: 'posts#info'
  post '/users/:id/verified' => 'users#verified', as: :verified_user
end

app/models/user_report.rb
class UserReport < ApplicationRecord
    has_one_attached :report_image, dependent: :destroy
end

app/controllers/user_reports_controller.rb
class UserReportsController < ApplicationController

  def new
    @user_report = UserReport.new
  end

  def create
    @user_report = UserReport.new(user_report_params)

    if @user_report.save
      # Invia l'email utilizzando il metodo mail della classe UserMailer
      UserMailer.report_email(@user_report).deliver_now

      redirect_to root_path, notice: 'La tua segnalazione è stata inviata con successo.'
    else
      render :new
    end
  end

  private

  def user_report_params
    params.require(:user_report).permit(:report_image, :topic, :email, :message)
  end
end

app/helpers/user_reports_helper.rb
module UserReportsHelper
end

app/views/user_reports/new.html.erb
<!--<br><br>
IMPOSTAZIONI
<button class="accordion">Info sviluppatori</button>
<div class="panel">
  <p>Lorem ipsum...</p>
</div>

<button class="accordion">Segnalazioni</button>
<div class="panel">
  <p>Quando riceviamo una segnalazione, la analizziamo e, se dovessimo stabilire che i nostri Standard della community di SocialNews sono stati violati, adottiamo le misure necessarie.Se segnali dei messaggi, potrebbero essere usati per migliorare i nostri sistemi di controllo di altri contenuti segnalati che potrebbero non rispettare i nostri Standard della community. Quando contattiamo la persona segnalata, non includiamo alcuna informazione sulla persona che ha compilato la segnalazione. Tieni presente che la segnalazione di contenuti non ne garantisce la rimozione.</p>
  <p><b>Segnalare contenuti:</b><br>- Profili<br>- Post<br>- Pagine<br>- Commenti<br>- Foto e video<br></p>
  <p><b>Inviaci la tua segnalazione e ti risponderemo il prima possibile!</b></p>
  <%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :"Inserisci la tua segnalazione", style: "display: block" %>
    <%= form.text_area :text_area, :cols => 60, :rows => 10 %>
  </div>
  
  <div>
    <%= form.submit"Invia" %>
  </div>
<% end %>
</div>

<button class="accordion">Proposte per migliorare app</button>
<div class="panel">
  <p><b>Aiutaci a migliorare SocialNews!</b></p>
  <p>Esprimi la tua opinione e proponi nuove idee per poter migliorare la nostra app.<br>Siamo sempre pronti per metterci in gioco e venirvi incontro per offrirvi la miglior esperienza possibile.</p>
  <%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :"Inserisci la tua proposta", style: "display: block" %>
    <%= form.text_area :text_area, :cols => 60, :rows => 10 %>
  </div>
  
  <div>
    <%= form.submit "Invia"%>
  </div>
<% end %>
</div>

<button class="accordion">Richiedi assistenza</button>
<div class="panel">
  <p><b>Tutto l'aiuto di cui hai bisogno!</b></p>
  <p>Cerchi informazioni nel centro assistenza su come risolvere i problemi relativi alle inserzioni, gestione degli account, problemi con il tuo profilo, password o altro?<br> Siamo lieti di offrire la nostra assistenza, potete contattarci:</p>
  <p><b>Numero verde:</b> 06123456789 <br><b>Email:</b> info@socialnews.com</p>
  <p>Oppure potete direttamente compilare il seguente modulo. Fornisci alcuni dettagli e ti offriremo la soluzione migliore.<br>Risponderemo il prima possibile!</p>
  <%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :"Inserisci il tuo problema", style: "display: block" %>
    <%= form.text_area :text_area , :cols => 60, :rows => 10%>
  </div>
  
  <div>
    <%= form.submit "Invia" %>
  </div>
<% end %>
</div>


<script>
var acc = document.getElementsByClassName("accordion");

    for (let i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function() {
        this.classList.toggle("active");
        for (j = 0; j < acc.length; j++) {
          if (j !== i)
            acc[j].nextElementSibling.style.maxHeight = null;
        }
        var panel = this.nextElementSibling;
        if (panel.style.maxHeight) {
          panel.style.maxHeight = null;
        } else {
          panel.style.maxHeight = panel.scrollHeight + "px";
        }
      });
    }
</script>
<h1>Segnala un problema</h1>
-->
<br>
<div class='container' style="width: 60%; background-color: white; text-align:center; margin-top: 80px;">
  <br>
  <h1>Nuova Segnalazione</h1>
  <br>

  <%= form_with model: @user_report, url: user_reports_path do |form| %>
    <div class="form-group">
      <%= form.label :topic %>
      <%= form.select :topic, ['Segnala un problema', 'Proponi nuove funzionalità', 'Richiedi assistenza', 'Richiedi verificato'] %>
    </div>
    <h5> Allega una foto alla tua segnalazione, oppure la foto di un documento se stai richiedendo il verificato.</h5>
    <div>
      <%= form.file_field :report_image %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :message %>
      <%= form.text_area :message, class: 'form-control' %>
    </div>
    <a class="btn feed-link"><%= form.submit 'Invia segnalazione', class: 'btn feed-link' %></a>
  <% end %>
  <br>
</div>