config/routes.rb
Rails.application.routes.draw do
  get 'user_reports/new'
  get 'user_reports/create'
  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth' }
  root "posts#index"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index, :new, :edit, :update, :destroy] do
    collection do
      post :index, :feed, :maps
    end
    resources :comments, only: [:create, :update, :destroy]
  end
  post '/posts/create', to: 'posts#create'
  resources :user_reports, only: [:new, :create]
  post '/posts/:id/like' => 'posts#like', as: :like_post
  post '/posts/:id/dislike' => 'posts#dislike', as: :dislike_post
  post '/posts/:id/favorite' => 'posts#favorite', as: :favorite_post
  resources :relationships,       only: [:create, :destroy]
  get '/users/:id/show_favorite', to: 'posts#show_favorite', as: :favorite_show
  get '/feed', to: 'posts#feed'
  get '/maps', to: 'posts#maps'
  get '/maps/:title', to: 'posts#maps'
  get '/info', to: 'posts#info'
  post '/users/:id/verified' => 'users#verified', as: :verified_user
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :dislikes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    belongs_to :user
    has_one_attached :image, dependent: :destroy
    def liked?(user)
        !!self.likes.find{|like| like.user_id == user.id}
    end
    def disliked?(user)
        !!self.dislikes.find{|dislike| dislike.user_id == user.id}
    end
    def favorited?(user)
        !!self.favorites.find{|favorite| favorite.user_id == user.id}
    end
    def self.all_category ; %w[Affari Cultura Politica Salute Spettacolo Sport Tecnologia] ; end
    validates :title, :presence=> true, length: {in: 2..150 }
    #validates :body, :presence=> true, length: {in: 100..1000}
    validates :category, :presence=> true, :inclusion => {:in => Post.all_category}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :maps]
  before_action :set_post, only: %i[ show edit update destroy ]
  def favorite
    @post = Post.all.find(params[:id])
    @favorite = Favorite.find_by user_id:current_user.id, post_id:@post.id
    if @favorite == nil
      Favorite.create(user_id: current_user.id, post_id: @post.id)
    else 
      @favorite.destroy
    end
  end
  def show_favorite
    @user = current_user
    favorited_ids = "SELECT post_id FROM favorites WHERE  user_id = :user_id"
    @pagy, @posts = pagy_countless(Post.where("id IN (#{favorited_ids})", user_id: params[:id]), items: 5)
    @comment = Comment.new
  end
  def maps
    @current_view = 'posts/maps'
    if(params[:title]!=nil)
      @title = params[:title]
      #@posts = Post.where("body LIKE ?", "%#{@title}%")
      @posts = Post.joins(:user).where("body LIKE ?", "%#{params[:title]}%")
                  .select("posts.*, users.name as author_name")
      respond_to do |format|
        format.json {render :json => @posts }
      end
    end
    @comment = Comment.new
  end
  
  def feed
    @current_view = 'posts/feed'
    following_ids = "SELECT followed_id FROM relationships WHERE  follower_id = :user_id"
    @pagy, @posts = pagy_countless(Post.where("user_id IN (#{following_ids})"), items: 5)
    @comment = Comment.new
    respond_to do |format|
      format.html # GET
      format.turbo_stream # POST
    end
    if params[:keyword].present?
      @pagy, @posts = pagy_countless(current_user.feed.where("title LIKE ? OR body LIKE ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%").order(rank: :desc), items: 5)
    elsif params[:category].present? 
      @pagy, @posts = pagy_countless(current_user.feed.where(category: params[:category]).order(rank: :desc), items: 5)
    else
      @pagy, @posts = pagy_countless(current_user.feed.order(rank: :desc), items: 5)
    end
  end
  # GET /posts or /posts.json
  def index
    if (Post.all.count < 15 && User.all.count != 0)
      GoogleNews.save_posts_from_google
    end
    @current_view = 'posts/index'   
    if params[:keyword].present?
      @pagy, @posts = pagy_countless(Post.where("title LIKE ? OR body LIKE ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%").order(rank: :desc), items: 5)
    elsif params[:category].present? 
      @pagy, @posts = pagy_countless(Post.where(category: params[:category]).order(rank: :desc), items: 5)
    else
      @pagy, @posts = pagy_countless(Post.order(rank: :desc), items: 5)
    end

    #query -> Post.order(:rank).reverse
    @comment = Comment.new
    respond_to do |format|
      format.html # GET
      format.turbo_stream # POST
    end
    
    #ricerca per categoria
    

  end

  # GET /posts/new
  def new
    @user = current_user
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts/create or /posts.json
  def create
		@user = current_user
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to user_path(current_user), notice: "Post was successfully created." }
        format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to user_path(current_user), notice: "Post was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def like
    @post = Post.all.find(params[:id])
    if(@post.liked?(current_user))
      @like = Like.find_by user_id:current_user.id, post_id:@post.id
      @like.destroy
      @post.rank -= 1
      @post.save
    else
      Like.create(user_id: current_user.id, post_id: @post.id)
      @post.rank += 1
      @post.save
      if(@post.disliked?(current_user))
        @dislike = Dislike.find_by user_id:current_user.id, post_id:@post.id
        @dislike.destroy
        @post.rank += 1
        @post.save
      end
    end
    #respond_to do |format|
    #  format.html { redirect_to posts_url}
    #  format.json { head :no_content }
    #end
    
  end
  def dislike
    @post = Post.all.find(params[:id])
    if(@post.disliked?(current_user))
      @dislike = Dislike.find_by user_id:current_user.id, post_id:@post.id
      @dislike.destroy
      @post.rank += 1
      @post.save
    else
      Dislike.create(user_id: current_user.id, post_id: @post.id)
      @post.rank -= 1
      @post.save
      if(@post.liked?(current_user))
        @like = Like.find_by user_id:current_user.id, post_id:@post.id
        @like.destroy
        @post.rank -= 1
        @post.save
      end
    end
    #respond_to do |format|
    #  format.html { redirect_to posts_url}
    #  format.json { head :no_content }
    #end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :category, :body, :image, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<% 
  max_id = Comment.maximum(:id)
  if max_id == nil
    max_id = 0
  end 
  post_id = post.id
%>

<div class='container post' style="background-color: white;">
  <br>
  <div class='container'>
    <div class='row'>
      <div class='col-11' style="padding-right: 0px;">
        <h5><b>
          <% if post.user.avatar.attached? %>
            <%= image_tag post.user.avatar, size: "40x40" %>
          <% else %>
            <%= image_tag "default_avatar.jpg", size: "40x40" %>
          <% end %>
          <%= link_to post.user.name, user_path(post.user.id), method: "get", class: "text-dark username", style: "padding-top: 7px;"%></b>
          <%= link_to post.user.surname, user_path(post.user.id), method: "get", class: "text-dark" %>
          <% if User.find(post.user.id).verified==1 %>
            <%= image_tag("verified-icon.jpg", style:"width: 15px; height: 15px;") %>
          <% end %>
        </h5></b>
      </div>
      <div class='col-1'>
        <% if user_signed_in? %>
            <div id="posts" data-name="<%= current_user.name %>" data-user_id="<%= current_user.id %>" data-max_id ="<%= max_id %>">
            <% if !post.favorited?(current_user) %>
          <button type="button" class="favorite" data-post_id="<%=post_id%>"><%= image_tag("empty-star.png", style:"width: 20px; height: 20px;", data: { empty_star_path: image_path('empty-star.png'), yellow_star_path: image_path('yellow-star.png')}) %></button>     
            <% else %>
          <button type="button" class="favorite" data-post_id="<%=post_id%>"><%= image_tag("yellow-star.png", style:"width: 20px; height: 20px;", data: { empty_star_path: image_path('empty-star.png'), yellow_star_path: image_path('yellow-star.png')}) %></button>     
            <% end %>
        <% else %>
          <div id="posts" data-max_id ="<%= max_id %>" data-post_id="<%= post.id %>">
        <% end %>
        </div>
          
      </div>
    </div>
  </div>
  <div class='col-12'>
    <p>
      <strong>#<%= post.category %></strong>
    </p>
  </div>
  <div class='col-12'>
    <p>
      <h5><%= post.title %></h5>
    </p>
  </div>
  <div class='container'>
    <div class='row'>
      <% if post.image.attached? || post.img_test != nil%>
        <div class='col-4'>
          <%= image_tag post.image, :style => "width: 100%; border-radius: 5px;" if post.image.attached?%>
          <%= image_tag post.img_test, :style => "width: 100%; border-radius: 5px;" if post.img_test != nil%>
        </div>
      <% end %>
      <div class='col-8'>
        <% if post.url != nil %>
          <p style="font-weight: normal;"><%= post.body %>...<a href = "<%= post.url %>" target="_blank" rel="noopener noreferrer">articolo completo</a></p>
        <% else %>
        <p style="font-weight: normal;"><%= post.body %></p>
        <% end %>
      </div>
    </div>
  </div>

  <br>

  <div class='container'>
    <div class='row'>
      <div class='col-4'>
        <% if user_signed_in? %>
          <div class="rank-buttons-div">
            <% if post.liked?(current_user) %>
              <button type="button" class="rank-btn up green-up" data-post_id="<%=post_id%>"><%= image_tag("green-up.png", data: { green_up_path: image_path('green-up.png'), white_up_path: image_path('white-up.png'), red_down_path: image_path("red-down.png"), white_down_path: image_path("white-down.png")}) %></button>     
              <span class="like-count" style='text-align: center; display: contents;' id="<%=post_id%>" style="padding-top: 20px;"><%= post.rank %></span>
              <button type="button" class="rank-btn down white-down" data-post_id="<%=post_id%>"><%= image_tag("white-down.png", data: { green_up_path: image_path('green-up.png'), white_up_path: image_path('white-up.png'), red_down_path: image_path("red-down.png"), white_down_path: image_path("white-down.png")}) %></button>     
            <% elsif !post.liked?(current_user) && post.disliked?(current_user)%>
              <button type="button" class="rank-btn up white-up" data-post_id="<%=post_id%>"><%= image_tag("white-up.png", data: { green_up_path: image_path('green-up.png'), white_up_path: image_path('white-up.png'), red_down_path: image_path("red-down.png"), white_down_path: image_path("white-down.png")}) %></button>     
              <span class="like-count" style='text-align: center; display: contents;' id="<%=post_id%>" style="padding-top: 20px;"><%= post.rank %></span>                
              <button type="button" class="rank-btn down red-down" data-post_id="<%=post_id%>"><%= image_tag("red-down.png", data: { green_up_path: image_path('green-up.png'), white_up_path: image_path('white-up.png'), red_down_path: image_path("red-down.png"), white_down_path: image_path("white-down.png")}) %></button>     
            <% else %>
              <button type="button" class="rank-btn up white-up" data-post_id="<%=post_id%>"><%= image_tag("white-up.png", data: { green_up_path: image_path('green-up.png'), white_up_path: image_path('white-up.png'), red_down_path: image_path("red-down.png"), white_down_path: image_path("white-down.png")}) %></button>     
              <span class="like-count" style='text-align: center; display: contents;' id="<%=post_id%>" style="padding-top: 20px;"><%= post.rank %></span>                  
              <button type="button" class="rank-btn down white-down" data-post_id="<%=post_id%>"><%= image_tag("white-down.png", data: { green_up_path: image_path('green-up.png'), white_up_path: image_path('white-up.png'), red_down_path: image_path("red-down.png"), white_down_path: image_path("white-down.png")}) %></button>     
            <% end %>
          </div>
        <% else %>
          <a href="/users/sign_in"><button type="button" class="rank-btn"><%= image_tag("white-up.png")%></button></a>     
          <span class="like-count" id="<%=post_id%>" style="padding-top: 20px;"><%= post.rank %></span>
          <a href="/users/sign_in"><button type="button" class="rank-btn"><%= image_tag("white-down.png")%></button></a>  
        <% end %> 
        </div>
      <div class='col-8'>
        <% #if post.comments.empty? %>
        <% #else %>
          <div class="comment-container" style="max-height: 100px; overflow: auto; overflow-x: hidden;">
              <ul class="comment-list" data-post-id="<%=post_id%>" data-image-path=<%=image_path('secchio.png')%>>
                <% post.comments.each do |r| %>
                  <% if r.visible %>
                    <div class="container">
                      <div class="row list-group-item" data-id="<%=r.id%>">
                        <div class="col-10">
                          <li class="list-group-item" style="word-wrap: break-word;">
                            <a href="/users/<%=r.user_id%>" style="margin-left: 0;"><div><%= User.find(r.user_id).name%></div></a><%=': '+ r.body %>
                          </li>
                        </div>
                        <div class="col-2">
                          <% if can? :destroy , r or (current_user!=nil and current_user.id == User.find(r.user_id).id) %>
                            <button type="button" class="delete btn" data-p_id="<%=r.post.id%>" data-id="<%=r.id%>"><%= image_tag("secchio.png", size: "20x20")%></button>     
                          <% end %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </ul>
          </div>

        <% #end %>
        <%= form_with model: [ post, @comment ], data: { post_id: post_id, max_id: max_id }, class: "comment-form" do |form| %>
          <% if @comment.errors.any? %>
            <div id="error_explanation">
              <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this review from being saved:</h4>
              <ul>
                <% @comment.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="col">
              <div class="field">
                <%= form.text_area :body, class: "comment-text", placeholder: "Lascia un commento", style: "width: 100%; height:30px;" %>
                <% if user_signed_in? %>
                  <div style="position: absolute; right: 25px; bottom: 5px; z-index: 1;">
                    <div style="display:none"> <%= form.select :user_id,[current_user.id] %> </div>
                    <%= image_submit_tag("add-comment.png", class: "comment-submit") %>
                  </div>
                <% end %>
              </div>  
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class='row'>
      <div class='col-2'></div>
      <div class='col-6'>  
        <script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=6410620c82a5320015aeb382&product=sop' async='async' ></script>
        <div class="sharethis-inline-share-buttons" data-url="<%= post.url %>"></div>
      </div>
      <div class='col-4'></div>
    </div>
    <% if can? :destroy, post or (current_user!=nil && current_user.id == post.user_id) %>
      <div class='row'>
        <% if !can? :destroy, post %>
          <div class="col-3"></div>
          <div class="col-3" style='text-align: center;'>
            <%= link_to "Modifica", edit_post_path(post), class: "btn feed-link" %>
          </div> 
          <div class="col-3" style='text-align: center; margin: 0px'>
            <%= if can? :destroy, post or (current_user!=nil and current_user.id == post.user_id) then button_to 'Elimina', post, class: "btn delete-link", method: :delete, data:{ confirm: 'Are you sure?' } end%>
          </div> 
          <div class="col-3"></div>
        <% else %>
          <div class="col-5"></div>
          <div class="col-2" style='text-align: center; margin: 0px'>
            <%= if can? :destroy, post or (current_user!=nil and current_user.id == post.user_id) then button_to 'Elimina', post, class: "btn delete-link", method: :delete, data:{ confirm: 'Are you sure?' } end%>
          </div> 
          <div class="col-5"></div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

<hr>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form_edit", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", root_path %>
</div>

app/views/posts/feed.html.erb
<p class="alert alert-danger" style="z-index: 1; margin-top: 78px; position: absolute;"><%= alert %></p>
<p class="alert alert-success" style="z-index: 1; margin-top: 78px;position: absolute;"><%= notice %></p>
<br>
<span class="page" style="display: none;"><%=@current_view%></span>
<div class="container-fluid double-bar" style="text-align: center; z-index:0;">
  <div class="row align-items-center d-flex justify-content-between">
    <% if current_user!=nil %>
      <div class="col-3" style="text-align:center;"></div>
      <div class="col" style="text-align:center;">
        <%= link_to "Home", root_path(), class: "btn feed-link home-buttons 1 font-size: 20px;" %>
      </div>
      <div class="col" style="text-align:center;">
        <%= link_to "Seguiti", feed_path(), class: "btn feed-link home-buttons 2 font-size: 20px;" %>
      </div>
      <div class="col" style="text-align:center;">
        <%= link_to "Esplora", maps_path(), class: "btn feed-link home-buttons 3 font-size: 20px;" %>
      </div>
      <div class="col-3" style="text-align:center;"></div>
    <% end %>
  </div>
  <div class="row align-items-center d-flex justify-content-between">
    <% i = 4%>
    <br>
    <div class="col"></div>
    <% Post.all_category.each do |category| %>
      <div class="col">
        <%= link_to category, feed_path(category: category), class: "category-link btn  home-buttons "+i.to_s %>
      </div>
      <% i += 1 %>
    <% end %>
    <div class="col-auto">
      <a href="#" class="btn home-buttons btn-link" id="show-form-btn"><i class="fa-solid fa-magnifying-glass" style="color: #14a112;"></i></a>
    </div>
    <div id="form-container" style="display: none; text-align: right; ">
      <%= form_tag(feed_path, method: "get") do %>
        <%= text_field_tag(:keyword, nil, placeholder: 'Cerca argomento...',class: "searchbar2") %>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
</div>

<script>
  $(document).ready(function() {
    // Aggiungi la classe "selected-category" al clic sul link della categoria
    $(".category-link").click(function() {
      $(".category-link").removeClass("selected-category");
      $(this).addClass("selected-category");
    });

    // Mostra/nascondi il form di ricerca
    $("#show-form-btn").click(function() {
      $("#form-container").toggle();
    });
  });
</script>

<br>

<div class="container posts" style="width: 60%;">
  <div class="news-text" style="text-align: center">
    <h1>News</h1>
  </div>
  <%= link_to image_tag("pencil.jpg", style: "width: 50px;"), new_post_path, class: " pencil"%>
  <br>
  <%= render @posts %>
</div>

app/views/posts/feed.turbo_stream.erb
<%= turbo_stream.append "posts" do %>
  <%= render partial: "post", collection: @posts %>
<% end %>

<%= turbo_stream.update "next_link" do %>
  <% if @pagy.next.present? %>
    <%= button_to "next", pagy_url_for(@pagy, @pagy.next) %>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<p class="alert alert-danger" style="z-index: 1; margin-top: 78px; position: absolute;"><%= alert %></p>
<p class="alert alert-success" style="z-index: 1; margin-top: 78px;position: absolute;"><%= notice %></p>
<br>
<span class="page" style="display: none;"><%=@current_view%></span>
<div class="container-fluid double-bar" style="text-align: center; z-index:0;">
  <div class="row align-items-center d-flex justify-content-between">
    <div class="col-3" style="text-align:center;"></div>
    <div class="col" style="text-align:center;">
      <%= link_to "Home", root_path(), class: "btn feed-link home-buttons 1 font-size: 20px;" %>
    </div>
    <% if current_user!=nil %>
      <div class="col" style="text-align:center;">
        <%= link_to "Seguiti", feed_path(), class: "btn feed-link home-buttons 2 font-size: 20px;" %>
      </div>
    <% end %>
    <div class="col" style="text-align:center;">
      <%= link_to "Esplora", maps_path(), class: "btn feed-link home-buttons 3 font-size: 20px;" %>
    </div>
    <div class="col-3" style="text-align:center;"></div>
  </div>
  <div class="row align-items-center d-flex justify-content-between">
    <% i = 4%>
    <br>
    <div class="col"></div>
    <% Post.all_category.each do |category| %>
      <div class="col">
        <%= link_to category, posts_path(category: category), class: "category-link btn  home-buttons "+i.to_s %>
      </div>
      <% i += 1 %>
    <% end %>
    <div class="col-auto">
      <a href="#" class="btn home-buttons btn-link" id="show-form-btn"><i class="fa-solid fa-magnifying-glass" style="color: #14a112;"></i></a>
    </div>
    <div id="form-container" style="display: none; text-align: right; ">
      <%= form_tag(posts_path, method: "get") do %>
        <%= text_field_tag(:keyword, nil, placeholder: 'Cerca argomento...',class: "searchbar2") %>
      <% end %>
    </div>
    <div class="col"></div>
  </div>
</div>

<script>
  $(document).ready(function() {
    // Aggiungi la classe "selected-category" al clic sul link della categoria
    $(".category-link").click(function() {
      $(".category-link").removeClass("selected-category");
      $(this).addClass("selected-category");
    });

    // Mostra/nascondi il form di ricerca
    $("#show-form-btn").click(function() {
      $("#form-container").toggle();
    });
  });
</script>

<br>

<div class="container posts" style="width: 60%;">
  <div class="news-text" style="text-align: center">
    <h1>News</h1>
  </div>
  <%= link_to image_tag("pencil.jpg", style: "width: 50px;"), new_post_path, class: " pencil"%>
  <br>
  <%= render @posts %>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    var alerts = document.querySelectorAll(".alert");

    alerts.forEach(function(alert) {
      if (alert.innerHTML.trim() !== "") {
        alert.classList.add("show");
      }
    });
  });

</script>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append "posts" do %>
  <%= render partial: "post", collection: @posts %>
<% end %>

<%= turbo_stream.update "next_link" do %>
  <% if @pagy.next.present? %>
    <%= button_to "next", pagy_url_for(@pagy, @pagy.next) %>
  <% end %>
<% end %>
<%= turbo_stream.update "prev_link" do %>
  <% if @pagy.prev.present? %>
    <%= button_to "prev", pagy_url_for(@pagy, @pagy.prev) %>
  <% end %>
<% end %>

app/views/posts/maps.html.erb
<br>
<div class="container-fluid double-bar" style="text-align: center; z-index:0;">
  <div class="row align-items-center d-flex justify-content-between">
    <div class="col-3" style="text-align:center;"></div>
    <div class="col" style="text-align:center;">
      <%= link_to "Home", root_path(), class: "btn feed-link home-buttons 1 font-size: 20px;" %>
    </div>
    <% if current_user!=nil %>
      <div class="col" style="text-align:center;">
        <%= link_to "Seguiti", feed_path(), class: "btn feed-link home-buttons 2 font-size: 20px;" %>
      </div>
    <% end %>
    <div class="col" style="text-align:center;">
      <%= link_to "Esplora", maps_path(), class: "btn feed-link home-buttons 3 font-size: 20px;" %>
    </div>
    <div class="col-3" style="text-align:center;"></div>
  </div>
</div>


<br>
<br>

<div id="map"></div>


<script>
    var map;
    var pos = {lat: 47.3312903, lng:11.1680664};
    function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {
            center: pos,
            zoom: 4,
            mapTypeControl: false,
            zoomControl: false,
            fullscreenControl: false,
            streetViewControl: false
        });

        var m = [
            getMarker(43.1754949, 13.0298647, 'Italia'),
            getMarker(46.6999999, 1.7153401, 'Francia'),
            getMarker(39.6489255, -3.3022213, 'Spagna'),
            getMarker(55.4207349, -2.7231131, 'Regno Unito'),
            getMarker(51.477977, 11.0692267, 'Germania')
        ];

        function getMarker(lat, lng, title){
            var marker = new google.maps.Marker({
            position : {lat: lat, lng: lng},
            map: map,
            title: title
            });

            marker.addListener('click', function() {
              var title = marker.get('title');
              // Esegui la chiamata AJAX al server per recuperare i post
              $.ajax({
                url: '/maps/' + title,
                type: 'GET',
                success: function(response) {
                  console.log(response);
                  $("#markerModalLabel").text(title);
                  $('#markerModal').modal('show');
                  var postsHtml = '';
                  response.forEach(function(post) {
                    postsHtml += '<div class="post">';
                    postsHtml += '#<strong class="post-cathergory">' + post.category + '</strong>';
                    postsHtml += '<h4 class="post-author">' + post.author_name + '</h4>';
                    postsHtml += '<h3 class="post-title">' + post.title + '</h3>';
                    postsHtml += '<div class="row">';
                    postsHtml += '<div class="col-4">';
                    postsHtml += '<img class="post-img" src=' + post.img_test + ' style="width: 100%; border-radius: 5px;" >';
                    postsHtml += '</div>';
                    postsHtml += '<div class="col-8">';
                    postsHtml += '<p class="post-body">' + post.body + '...<a href = "' + post.url + '" target="_blank" rel="noopener noreferrer">Articolo completo</a></p>';
                    postsHtml += '</div>';
                    postsHtml += '</div>';
                    postsHtml += '</div>';
                    postsHtml += '<hr>';
                  });
                  $('#markerModal .modal-body').html(postsHtml);
                },

                error: function() {
                  alert('Errore durante il caricamento dei post.');
                }
              });
            });

        }
    }

</script>

<style>

#map {
  height: 500px;
}

/* 
 * Optional: Makes the sample page fill the window. 
 */
html,
body {
  height: 100%;
  margin: 0;
  padding: 0;
}

</style>


<!-- Modal -->
<div class="modal fade" id="markerModal" tabindex="-1" role="dialog" aria-labelledby="markerModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:600px;">
      <div class="modal-header">
        <h5 class="modal-title" id="markerModalLabel">Titolo del marker</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn delete-link" data-dismiss="modal">Chiudi</button>
      </div>
    </div>
  </div>
</div>