config/routes.rb
Rails.application.routes.draw do
  get 'user_reports/new'
  get 'user_reports/create'
  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth' }
  root "posts#index"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:index, :new, :edit, :update, :destroy] do
    collection do
      post :index, :feed, :maps
    end
    resources :comments, only: [:create, :update, :destroy]
  end
  post '/posts/create', to: 'posts#create'
  resources :user_reports, only: [:new, :create]
  post '/posts/:id/like' => 'posts#like', as: :like_post
  post '/posts/:id/dislike' => 'posts#dislike', as: :dislike_post
  post '/posts/:id/favorite' => 'posts#favorite', as: :favorite_post
  resources :relationships,       only: [:create, :destroy]
  get '/users/:id/show_favorite', to: 'posts#show_favorite', as: :favorite_show
  get '/feed', to: 'posts#feed'
  get '/maps', to: 'posts#maps'
  get '/maps/:title', to: 'posts#maps'
  get '/info', to: 'posts#info'
  post '/users/:id/verified' => 'users#verified', as: :verified_user
end

app/views/layouts/application.html.erb
<%= javascript_import_module_tag "post" %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- primo script google translate-->
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<!--Script Google Maps-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDNF-rSthM99v10XV-x25hDT-bBpxfTKY4&callback=initMap&v=weekly"async defer></script>
<!-- fine google translate-->
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<%= stylesheet_link_tag 'post' %>


<!DOCTYPE html>
<html>
  <head>
    <title>SocialNews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>
  <body>
  <% if current_user!=nil %>
    <% if (current_user.email == "admin@gmail.com" )%>
      <% current_user.admin! %>
    <%end%>
  <%end%>
  <% if show_navbar? %>
    <nav class="navbar navbar-fixed-top" style="z-index:1; ">
      <%= link_to root_path() do %>
        <%= image_tag("icona.png", size: "110x60") %>
      <% end %>
      
      <% if user_signed_in? %>
        <%= form_tag(users_path, method: "get") do %>
          <div class="searchbar-container">
            <span class="fa fa-search"></span>
            <%= text_field_tag(:user_name ,nil, placeholder: 'Cerca utente...',class: "searchbar1") %>
          </div>
        <% end %>

        <i class="fas fa-language fa-lg clickable" onclick="toggleWidget()"></i>
      <div id="google_translate_element" style="display: none;"></div>

      <script>
        var widgetShown = false;
        function toggleWidget() {
          if (widgetShown) {
            document.getElementById("google_translate_element").style.display = "none";
            widgetShown = false;
          } else {
            new google.translate.TranslateElement({pageLanguage: 'it'}, 'google_translate_element');
            document.getElementById("google_translate_element").style.display = "block";
            widgetShown = true;
          }
        }
      </script>

        <%= link_to  "#", class: "navbar-right dropdown-toggle", data: { toggle: "dropdown" } do %>
          <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, size: "30x30" %>
          <% else %>
            <%= image_tag "default_avatar.jpg", size: "30x30" %>
          <% end %>
        <% end %>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="padding: 5 15;">
            <li>
              <% if can? :all, @user %>
                <%= link_to "<i class='fas fa-users'></i> Tutti gli utenti".html_safe, users_path, method: "get", style: "color: black" %>
              <% else %>
                <%= link_to "<i class='fas fa-cog'></i> Impostazioni".html_safe, new_user_report_path(), style: "color: black" %>
              <% end %>
            </li>
            <li>
             <%= link_to "<i class='fas fa-user'></i> Il mio profilo".html_safe, user_path(current_user.id), method: "get", class:"mio-profilo", style: "color: black" %>
            </li>
            <li>
             <%= link_to "<i class='fas fa-sign-out-alt'></i> Logout".html_safe, destroy_user_session_path, method: :delete, style: "color: red" %>
            </li>
          </ul>

      <% else %>
        <%= link_to "Accedi o registrati",new_user_session_path %>
      <% end %>
    </nav>
  <% end %>
  <%= yield %>
  <div class="container" style="text-align:center;">
    <div class="row">
      <div class="col-6">
        <% if @pagy!=nil && @pagy.prev %>
          <div id="prev_link">
            <%= link_to pagy_url_for(@pagy, @pagy.prev) do %>
              <%= image_tag "button_prev_page.png", alt: "Pagina precedente", style: "width:30px;"%>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-6">
        <% if @pagy!=nil && @pagy.next   %>
          <div id="next_link">
            <%= link_to pagy_url_for(@pagy, @pagy.next) do %>
              <%= image_tag "button_next_page.png", alt: "Prossima pagina", style: "width:30px;"%>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% notice if notice %>
  <% alert if alert %> 
  <br>
  </body>
</html>